### ISSUE TITLE
Criar BD

### ISSUE THREAD

**Issue by thewillyan** [petcompufc/oci-novo-back#1]
- [x] Criar modelo do banco de dados (PostgresSQL).
- [x] Configurar setup automático com docker.
- [x] Adicionar dados te template no banco.

**Comment by thewillyan** [comment]
# Proposta de modelo

- 1 BD de API
- 1 BD de Conteúdo do site
- Tipos de usuário
    - Anônimo
    - Escola
    - Aluno
    - Administrador
- Todos os usuários podem visualizar o conteúdo do site
- Alunos solicitam a inscrição para as escolas
- Escolas confirmam a inscrição
- Administrador edita o conteúdo do site de visualiza metadados da olímpiada
- Anônimo apenas pode criar conta

**Comment by EstherMart** [comment]
Acesso aos modelos de BD criados: https://drive.google.com/file/d/1k8Wppn8qDhvlpSCDKIJkF40IevD_vEfp/view?usp=sharing

**Comment by thewillyan** [comment]
task: criar um arquivo em `db/setup/3-inserir-dados.sql`.
