### ISSUE TITLE
implementar endpoint de cadastro de usuario

### ISSUE THREAD

**Issue by thewillyan** [petcompufc/oci-novo-back#6]
Definir endpoint `/api/<versao>/cadastro` que cadastra um usuário de um dado cargo sendo eles aluno ou escola. Usuários de cargo Petiano deverão ser cadastrados através de outro endpoint que será definido posteriormente.

Os dados tem a seguintes propridades:
 
- Devem ser repassados para servidor via método `POST` exclusivamente.
- Tem formato JSON.
- O campo `"dados"` deve corresponder ao dados do usuário e os dados do cargo, ou seqa, as informações necessárias para que o usuário seja inserido no BD.
- Devem conter um campo de `id` (o qual especifica qual o `id_global` do usuario que está chamando a API) que deve ser usado para determinar o cargo do usuário e, consequentemente, para validação.
    - Um usuário anonimo cria usuarios do tipo Escola e Aluno (escolas devem ser iseridas na tabela para avaliação).
    - Um usuário do tipo escola, se já validados, pode criar alunos.

A resposta da API deve ser dada em formato JSON e deve constar as informações necessárias para efetuar o "login" do usuário no cliente, como o id de usuário e o cargo.

As operações no banco de dados devem ser feitas pelo usuário `api_user`. 

---

**Informações quanto ao futuro**:
Para aumentar a segurança nessa infraestrutura a comunicação da Backend será isolada da rede, ou seja, apenas a frontend ficará esposta pra internet publica, assim terceiros não poderão fazer requests para a back. Outras questões serão consideradas posteriormente, em caso de falhas de segurança, issues deverão ser criadas pela primeira pessoa que a notou.

**Comment by thewillyan** [comment]
Recomendo que leiam isso antes de implementar: [Building Robust Web Applications with Fiber: Best Practices](https://www.linkedin.com/pulse/building-robust-web-applications-fiber-best-practices-reza-mousavian-1e)

**Comment by joaovitormgv** [comment]
O que falta:
- Validação de dados
- atualizar permissões GRANT api_user (permitir inserção na table endereco)
- Se necessário, implementar middlewares de autenticação
